#![allow(non_snake_case, dead_code)]

#[no_mangle] pub extern "C" fn glAccum() {}
#[no_mangle] pub extern "C" fn glAlphaFunc() {}
#[no_mangle] pub extern "C" fn glAreTexturesResident() {}
#[no_mangle] pub extern "C" fn glArrayElement() {}
#[no_mangle] pub extern "C" fn glBegin() {}
#[no_mangle] pub extern "C" fn glBindTexture() {}
#[no_mangle] pub extern "C" fn glBitmap() {}
#[no_mangle] pub extern "C" fn glBlendFunc() {}
#[no_mangle] pub extern "C" fn glCallList() {}
#[no_mangle] pub extern "C" fn glCallLists() {}
#[no_mangle] pub extern "C" fn glClear() {}
#[no_mangle] pub extern "C" fn glClearAccum() {}
#[no_mangle] pub extern "C" fn glClearColor() {}
#[no_mangle] pub extern "C" fn glClearDepth() {}
#[no_mangle] pub extern "C" fn glClearIndex() {}
#[no_mangle] pub extern "C" fn glClearStencil() {}
#[no_mangle] pub extern "C" fn glClipPlane() {}
#[no_mangle] pub extern "C" fn glColor3b() {}
#[no_mangle] pub extern "C" fn glColor3bv() {}
#[no_mangle] pub extern "C" fn glColor3d() {}
#[no_mangle] pub extern "C" fn glColor3dv() {}
#[no_mangle] pub extern "C" fn glColor3f() {}
#[no_mangle] pub extern "C" fn glColor3fv() {}
#[no_mangle] pub extern "C" fn glColor3i() {}
#[no_mangle] pub extern "C" fn glColor3iv() {}
#[no_mangle] pub extern "C" fn glColor3s() {}
#[no_mangle] pub extern "C" fn glColor3sv() {}
#[no_mangle] pub extern "C" fn glColor3ub() {}
#[no_mangle] pub extern "C" fn glColor3ubv() {}
#[no_mangle] pub extern "C" fn glColor3ui() {}
#[no_mangle] pub extern "C" fn glColor3uiv() {}
#[no_mangle] pub extern "C" fn glColor3us() {}
#[no_mangle] pub extern "C" fn glColor3usv() {}
#[no_mangle] pub extern "C" fn glColor4b() {}
#[no_mangle] pub extern "C" fn glColor4bv() {}
#[no_mangle] pub extern "C" fn glColor4d() {}
#[no_mangle] pub extern "C" fn glColor4dv() {}
#[no_mangle] pub extern "C" fn glColor4f() {}
#[no_mangle] pub extern "C" fn glColor4fv() {}
#[no_mangle] pub extern "C" fn glColor4i() {}
#[no_mangle] pub extern "C" fn glColor4iv() {}
#[no_mangle] pub extern "C" fn glColor4s() {}
#[no_mangle] pub extern "C" fn glColor4sv() {}
#[no_mangle] pub extern "C" fn glColor4ub() {}
#[no_mangle] pub extern "C" fn glColor4ubv() {}
#[no_mangle] pub extern "C" fn glColor4ui() {}
#[no_mangle] pub extern "C" fn glColor4uiv() {}
#[no_mangle] pub extern "C" fn glColor4us() {}
#[no_mangle] pub extern "C" fn glColor4usv() {}
#[no_mangle] pub extern "C" fn glColorMask() {}
#[no_mangle] pub extern "C" fn glColorMaterial() {}
#[no_mangle] pub extern "C" fn glColorPointer() {}
#[no_mangle] pub extern "C" fn glCopyPixels() {}
#[no_mangle] pub extern "C" fn glCopyTexImage1D() {}
#[no_mangle] pub extern "C" fn glCopyTexImage2D() {}
#[no_mangle] pub extern "C" fn glCopyTexSubImage1D() {}
#[no_mangle] pub extern "C" fn glCopyTexSubImage2D() {}
#[no_mangle] pub extern "C" fn glCullFace() {}
#[no_mangle] pub extern "C" fn glDebugEntry() {}
#[no_mangle] pub extern "C" fn glDeleteLists() {}
#[no_mangle] pub extern "C" fn glDeleteTextures() {}
#[no_mangle] pub extern "C" fn glDepthFunc() {}
#[no_mangle] pub extern "C" fn glDepthMask() {}
#[no_mangle] pub extern "C" fn glDepthRange() {}
#[no_mangle] pub extern "C" fn glDisable() {}
#[no_mangle] pub extern "C" fn glDisableClientState() {}
#[no_mangle] pub extern "C" fn glDrawArrays() {}
#[no_mangle] pub extern "C" fn glDrawBuffer() {}
#[no_mangle] pub extern "C" fn glDrawElements() {}
#[no_mangle] pub extern "C" fn glDrawPixels() {}
#[no_mangle] pub extern "C" fn glEdgeFlag() {}
#[no_mangle] pub extern "C" fn glEdgeFlagPointer() {}
#[no_mangle] pub extern "C" fn glEdgeFlagv() {}
#[no_mangle] pub extern "C" fn glEnable() {}
#[no_mangle] pub extern "C" fn glEnableClientState() {}
#[no_mangle] pub extern "C" fn glEnd() {}
#[no_mangle] pub extern "C" fn glEndList() {}
#[no_mangle] pub extern "C" fn glEvalCoord1d() {}
#[no_mangle] pub extern "C" fn glEvalCoord1dv() {}
#[no_mangle] pub extern "C" fn glEvalCoord1f() {}
#[no_mangle] pub extern "C" fn glEvalCoord1fv() {}
#[no_mangle] pub extern "C" fn glEvalCoord2d() {}
#[no_mangle] pub extern "C" fn glEvalCoord2dv() {}
#[no_mangle] pub extern "C" fn glEvalCoord2f() {}
#[no_mangle] pub extern "C" fn glEvalCoord2fv() {}
#[no_mangle] pub extern "C" fn glEvalMesh1() {}
#[no_mangle] pub extern "C" fn glEvalMesh2() {}
#[no_mangle] pub extern "C" fn glEvalPoint1() {}
#[no_mangle] pub extern "C" fn glEvalPoint2() {}
#[no_mangle] pub extern "C" fn glFeedbackBuffer() {}
#[no_mangle] pub extern "C" fn glFinish() {}
#[no_mangle] pub extern "C" fn glFlush() {}
#[no_mangle] pub extern "C" fn glFogf() {}
#[no_mangle] pub extern "C" fn glFogfv() {}
#[no_mangle] pub extern "C" fn glFogi() {}
#[no_mangle] pub extern "C" fn glFogiv() {}
#[no_mangle] pub extern "C" fn glFrontFace() {}
#[no_mangle] pub extern "C" fn glFrustum() {}
#[no_mangle] pub extern "C" fn glGenLists() {}
#[no_mangle] pub extern "C" fn glGenTextures() {}
#[no_mangle] pub extern "C" fn glGetBooleanv() {}
#[no_mangle] pub extern "C" fn glGetClipPlane() {}
#[no_mangle] pub extern "C" fn glGetDoublev() {}
#[no_mangle] pub extern "C" fn glGetError() {}
#[no_mangle] pub extern "C" fn glGetFloatv() {}
#[no_mangle] pub extern "C" fn glGetIntegerv() {}
#[no_mangle] pub extern "C" fn glGetLightfv() {}
#[no_mangle] pub extern "C" fn glGetLightiv() {}
#[no_mangle] pub extern "C" fn glGetMapdv() {}
#[no_mangle] pub extern "C" fn glGetMapfv() {}
#[no_mangle] pub extern "C" fn glGetMapiv() {}
#[no_mangle] pub extern "C" fn glGetMaterialfv() {}
#[no_mangle] pub extern "C" fn glGetMaterialiv() {}
#[no_mangle] pub extern "C" fn glGetPixelMapfv() {}
#[no_mangle] pub extern "C" fn glGetPixelMapuiv() {}
#[no_mangle] pub extern "C" fn glGetPixelMapusv() {}
#[no_mangle] pub extern "C" fn glGetPointerv() {}
#[no_mangle] pub extern "C" fn glGetPolygonStipple() {}
#[no_mangle] pub extern "C" fn glGetString() {}
#[no_mangle] pub extern "C" fn glGetTexEnvfv() {}
#[no_mangle] pub extern "C" fn glGetTexEnviv() {}
#[no_mangle] pub extern "C" fn glGetTexGendv() {}
#[no_mangle] pub extern "C" fn glGetTexGenfv() {}
#[no_mangle] pub extern "C" fn glGetTexGeniv() {}
#[no_mangle] pub extern "C" fn glGetTexImage() {}
#[no_mangle] pub extern "C" fn glGetTexLevelParameterfv() {}
#[no_mangle] pub extern "C" fn glGetTexLevelParameteriv() {}
#[no_mangle] pub extern "C" fn glGetTexParameterfv() {}
#[no_mangle] pub extern "C" fn glGetTexParameteriv() {}
#[no_mangle] pub extern "C" fn glHint() {}
#[no_mangle] pub extern "C" fn glIndexMask() {}
#[no_mangle] pub extern "C" fn glIndexPointer() {}
#[no_mangle] pub extern "C" fn glIndexd() {}
#[no_mangle] pub extern "C" fn glIndexdv() {}
#[no_mangle] pub extern "C" fn glIndexf() {}
#[no_mangle] pub extern "C" fn glIndexfv() {}
#[no_mangle] pub extern "C" fn glIndexi() {}
#[no_mangle] pub extern "C" fn glIndexiv() {}
#[no_mangle] pub extern "C" fn glIndexs() {}
#[no_mangle] pub extern "C" fn glIndexsv() {}
#[no_mangle] pub extern "C" fn glIndexub() {}
#[no_mangle] pub extern "C" fn glIndexubv() {}
#[no_mangle] pub extern "C" fn glInitNames() {}
#[no_mangle] pub extern "C" fn glInterleavedArrays() {}
#[no_mangle] pub extern "C" fn glIsEnabled() {}
#[no_mangle] pub extern "C" fn glIsList() {}
#[no_mangle] pub extern "C" fn glIsTexture() {}
#[no_mangle] pub extern "C" fn glLightModelf() {}
#[no_mangle] pub extern "C" fn glLightModelfv() {}
#[no_mangle] pub extern "C" fn glLightModeli() {}
#[no_mangle] pub extern "C" fn glLightModeliv() {}
#[no_mangle] pub extern "C" fn glLightf() {}
#[no_mangle] pub extern "C" fn glLightfv() {}
#[no_mangle] pub extern "C" fn glLighti() {}
#[no_mangle] pub extern "C" fn glLightiv() {}
#[no_mangle] pub extern "C" fn glLineStipple() {}
#[no_mangle] pub extern "C" fn glLineWidth() {}
#[no_mangle] pub extern "C" fn glListBase() {}
#[no_mangle] pub extern "C" fn glLoadIdentity() {}
#[no_mangle] pub extern "C" fn glLoadMatrixd() {}
#[no_mangle] pub extern "C" fn glLoadMatrixf() {}
#[no_mangle] pub extern "C" fn glLoadName() {}
#[no_mangle] pub extern "C" fn glLogicOp() {}
#[no_mangle] pub extern "C" fn glMap1d() {}
#[no_mangle] pub extern "C" fn glMap1f() {}
#[no_mangle] pub extern "C" fn glMap2d() {}
#[no_mangle] pub extern "C" fn glMap2f() {}
#[no_mangle] pub extern "C" fn glMapGrid1d() {}
#[no_mangle] pub extern "C" fn glMapGrid1f() {}
#[no_mangle] pub extern "C" fn glMapGrid2d() {}
#[no_mangle] pub extern "C" fn glMapGrid2f() {}
#[no_mangle] pub extern "C" fn glMaterialf() {}
#[no_mangle] pub extern "C" fn glMaterialfv() {}
#[no_mangle] pub extern "C" fn glMateriali() {}
#[no_mangle] pub extern "C" fn glMaterialiv() {}
#[no_mangle] pub extern "C" fn glMatrixMode() {}
#[no_mangle] pub extern "C" fn glMultMatrixd() {}
#[no_mangle] pub extern "C" fn glMultMatrixf() {}
#[no_mangle] pub extern "C" fn glNewList() {}
#[no_mangle] pub extern "C" fn glNormal3b() {}
#[no_mangle] pub extern "C" fn glNormal3bv() {}
#[no_mangle] pub extern "C" fn glNormal3d() {}
#[no_mangle] pub extern "C" fn glNormal3dv() {}
#[no_mangle] pub extern "C" fn glNormal3f() {}
#[no_mangle] pub extern "C" fn glNormal3fv() {}
#[no_mangle] pub extern "C" fn glNormal3i() {}
#[no_mangle] pub extern "C" fn glNormal3iv() {}
#[no_mangle] pub extern "C" fn glNormal3s() {}
#[no_mangle] pub extern "C" fn glNormal3sv() {}
#[no_mangle] pub extern "C" fn glNormalPointer() {}
#[no_mangle] pub extern "C" fn glOrtho() {}
#[no_mangle] pub extern "C" fn glPassThrough() {}
#[no_mangle] pub extern "C" fn glPixelMapfv() {}
#[no_mangle] pub extern "C" fn glPixelMapuiv() {}
#[no_mangle] pub extern "C" fn glPixelMapusv() {}
#[no_mangle] pub extern "C" fn glPixelStoref() {}
#[no_mangle] pub extern "C" fn glPixelStorei() {}
#[no_mangle] pub extern "C" fn glPixelTransferf() {}
#[no_mangle] pub extern "C" fn glPixelTransferi() {}
#[no_mangle] pub extern "C" fn glPixelZoom() {}
#[no_mangle] pub extern "C" fn glPointSize() {}
#[no_mangle] pub extern "C" fn glPolygonMode() {}
#[no_mangle] pub extern "C" fn glPolygonOffset() {}
#[no_mangle] pub extern "C" fn glPolygonStipple() {}
#[no_mangle] pub extern "C" fn glPopAttrib() {}
#[no_mangle] pub extern "C" fn glPopClientAttrib() {}
#[no_mangle] pub extern "C" fn glPopMatrix() {}
#[no_mangle] pub extern "C" fn glPopName() {}
#[no_mangle] pub extern "C" fn glPrioritizeTextures() {}
#[no_mangle] pub extern "C" fn glPushAttrib() {}
#[no_mangle] pub extern "C" fn glPushClientAttrib() {}
#[no_mangle] pub extern "C" fn glPushMatrix() {}
#[no_mangle] pub extern "C" fn glPushName() {}
#[no_mangle] pub extern "C" fn glRasterPos2d() {}
#[no_mangle] pub extern "C" fn glRasterPos2dv() {}
#[no_mangle] pub extern "C" fn glRasterPos2f() {}
#[no_mangle] pub extern "C" fn glRasterPos2fv() {}
#[no_mangle] pub extern "C" fn glRasterPos2i() {}
#[no_mangle] pub extern "C" fn glRasterPos2iv() {}
#[no_mangle] pub extern "C" fn glRasterPos2s() {}
#[no_mangle] pub extern "C" fn glRasterPos2sv() {}
#[no_mangle] pub extern "C" fn glRasterPos3d() {}
#[no_mangle] pub extern "C" fn glRasterPos3dv() {}
#[no_mangle] pub extern "C" fn glRasterPos3f() {}
#[no_mangle] pub extern "C" fn glRasterPos3fv() {}
#[no_mangle] pub extern "C" fn glRasterPos3i() {}
#[no_mangle] pub extern "C" fn glRasterPos3iv() {}
#[no_mangle] pub extern "C" fn glRasterPos3s() {}
#[no_mangle] pub extern "C" fn glRasterPos3sv() {}
#[no_mangle] pub extern "C" fn glRasterPos4d() {}
#[no_mangle] pub extern "C" fn glRasterPos4dv() {}
#[no_mangle] pub extern "C" fn glRasterPos4f() {}
#[no_mangle] pub extern "C" fn glRasterPos4fv() {}
#[no_mangle] pub extern "C" fn glRasterPos4i() {}
#[no_mangle] pub extern "C" fn glRasterPos4iv() {}
#[no_mangle] pub extern "C" fn glRasterPos4s() {}
#[no_mangle] pub extern "C" fn glRasterPos4sv() {}
#[no_mangle] pub extern "C" fn glReadBuffer() {}
#[no_mangle] pub extern "C" fn glReadPixels() {}
#[no_mangle] pub extern "C" fn glRectd() {}
#[no_mangle] pub extern "C" fn glRectdv() {}
#[no_mangle] pub extern "C" fn glRectf() {}
#[no_mangle] pub extern "C" fn glRectfv() {}
#[no_mangle] pub extern "C" fn glRecti() {}
#[no_mangle] pub extern "C" fn glRectiv() {}
#[no_mangle] pub extern "C" fn glRects() {}
#[no_mangle] pub extern "C" fn glRectsv() {}
#[no_mangle] pub extern "C" fn glRenderMode() {}
#[no_mangle] pub extern "C" fn glRotated() {}
#[no_mangle] pub extern "C" fn glRotatef() {}
#[no_mangle] pub extern "C" fn glScaled() {}
#[no_mangle] pub extern "C" fn glScalef() {}
#[no_mangle] pub extern "C" fn glScissor() {}
#[no_mangle] pub extern "C" fn glSelectBuffer() {}
#[no_mangle] pub extern "C" fn glShadeModel() {}
#[no_mangle] pub extern "C" fn glStencilFunc() {}
#[no_mangle] pub extern "C" fn glStencilMask() {}
#[no_mangle] pub extern "C" fn glStencilOp() {}
#[no_mangle] pub extern "C" fn glTexCoord1d() {}
#[no_mangle] pub extern "C" fn glTexCoord1dv() {}
#[no_mangle] pub extern "C" fn glTexCoord1f() {}
#[no_mangle] pub extern "C" fn glTexCoord1fv() {}
#[no_mangle] pub extern "C" fn glTexCoord1i() {}
#[no_mangle] pub extern "C" fn glTexCoord1iv() {}
#[no_mangle] pub extern "C" fn glTexCoord1s() {}
#[no_mangle] pub extern "C" fn glTexCoord1sv() {}
#[no_mangle] pub extern "C" fn glTexCoord2d() {}
#[no_mangle] pub extern "C" fn glTexCoord2dv() {}
#[no_mangle] pub extern "C" fn glTexCoord2f() {}
#[no_mangle] pub extern "C" fn glTexCoord2fv() {}
#[no_mangle] pub extern "C" fn glTexCoord2i() {}
#[no_mangle] pub extern "C" fn glTexCoord2iv() {}
#[no_mangle] pub extern "C" fn glTexCoord2s() {}
#[no_mangle] pub extern "C" fn glTexCoord2sv() {}
#[no_mangle] pub extern "C" fn glTexCoord3d() {}
#[no_mangle] pub extern "C" fn glTexCoord3dv() {}
#[no_mangle] pub extern "C" fn glTexCoord3f() {}
#[no_mangle] pub extern "C" fn glTexCoord3fv() {}
#[no_mangle] pub extern "C" fn glTexCoord3i() {}
#[no_mangle] pub extern "C" fn glTexCoord3iv() {}
#[no_mangle] pub extern "C" fn glTexCoord3s() {}
#[no_mangle] pub extern "C" fn glTexCoord3sv() {}
#[no_mangle] pub extern "C" fn glTexCoord4d() {}
#[no_mangle] pub extern "C" fn glTexCoord4dv() {}
#[no_mangle] pub extern "C" fn glTexCoord4f() {}
#[no_mangle] pub extern "C" fn glTexCoord4fv() {}
#[no_mangle] pub extern "C" fn glTexCoord4i() {}
#[no_mangle] pub extern "C" fn glTexCoord4iv() {}
#[no_mangle] pub extern "C" fn glTexCoord4s() {}
#[no_mangle] pub extern "C" fn glTexCoord4sv() {}
#[no_mangle] pub extern "C" fn glTexCoordPointer() {}
#[no_mangle] pub extern "C" fn glTexEnvf() {}
#[no_mangle] pub extern "C" fn glTexEnvfv() {}
#[no_mangle] pub extern "C" fn glTexEnvi() {}
#[no_mangle] pub extern "C" fn glTexEnviv() {}
#[no_mangle] pub extern "C" fn glTexGend() {}
#[no_mangle] pub extern "C" fn glTexGendv() {}
#[no_mangle] pub extern "C" fn glTexGenf() {}
#[no_mangle] pub extern "C" fn glTexGenfv() {}
#[no_mangle] pub extern "C" fn glTexGeni() {}
#[no_mangle] pub extern "C" fn glTexGeniv() {}
#[no_mangle] pub extern "C" fn glTexImage1D() {}
#[no_mangle] pub extern "C" fn glTexImage2D() {}
#[no_mangle] pub extern "C" fn glTexParameterf() {}
#[no_mangle] pub extern "C" fn glTexParameterfv() {}
#[no_mangle] pub extern "C" fn glTexParameteri() {}
#[no_mangle] pub extern "C" fn glTexParameteriv() {}
#[no_mangle] pub extern "C" fn glTexSubImage1D() {}
#[no_mangle] pub extern "C" fn glTexSubImage2D() {}
#[no_mangle] pub extern "C" fn glTranslated() {}
#[no_mangle] pub extern "C" fn glTranslatef() {}
#[no_mangle] pub extern "C" fn glVertex2d() {}
#[no_mangle] pub extern "C" fn glVertex2dv() {}
#[no_mangle] pub extern "C" fn glVertex2f() {}
#[no_mangle] pub extern "C" fn glVertex2fv() {}
#[no_mangle] pub extern "C" fn glVertex2i() {}
#[no_mangle] pub extern "C" fn glVertex2iv() {}
#[no_mangle] pub extern "C" fn glVertex2s() {}
#[no_mangle] pub extern "C" fn glVertex2sv() {}
#[no_mangle] pub extern "C" fn glVertex3d() {}
#[no_mangle] pub extern "C" fn glVertex3dv() {}
#[no_mangle] pub extern "C" fn glVertex3f() {}
#[no_mangle] pub extern "C" fn glVertex3fv() {}
#[no_mangle] pub extern "C" fn glVertex3i() {}
#[no_mangle] pub extern "C" fn glVertex3iv() {}
#[no_mangle] pub extern "C" fn glVertex3s() {}
#[no_mangle] pub extern "C" fn glVertex3sv() {}
#[no_mangle] pub extern "C" fn glVertex4d() {}
#[no_mangle] pub extern "C" fn glVertex4dv() {}
#[no_mangle] pub extern "C" fn glVertex4f() {}
#[no_mangle] pub extern "C" fn glVertex4fv() {}
#[no_mangle] pub extern "C" fn glVertex4i() {}
#[no_mangle] pub extern "C" fn glVertex4iv() {}
#[no_mangle] pub extern "C" fn glVertex4s() {}
#[no_mangle] pub extern "C" fn glVertex4sv() {}
#[no_mangle] pub extern "C" fn glVertexPointer() {}
#[no_mangle] pub extern "C" fn glViewport() {}
#[no_mangle] pub extern "C" fn wglChoosePixelFormat() {}
#[no_mangle] pub extern "C" fn wglCopyContext() {}
#[no_mangle] pub extern "C" fn wglCreateContext() {}
#[no_mangle] pub extern "C" fn wglCreateLayerContext() {}
#[no_mangle] pub extern "C" fn wglDeleteContext() {}
#[no_mangle] pub extern "C" fn wglDescribeLayerPlane() {}
#[no_mangle] pub extern "C" fn wglDescribePixelFormat() {}
#[no_mangle] pub extern "C" fn wglGetCurrentContext() {}
#[no_mangle] pub extern "C" fn wglGetCurrentDC() {}
#[no_mangle] pub extern "C" fn wglGetDefaultProcAddress() {}
#[no_mangle] pub extern "C" fn wglGetLayerPaletteEntries() {}
#[no_mangle] pub extern "C" fn wglGetPixelFormat() {}
#[no_mangle] pub extern "C" fn wglGetProcAddress() {}
#[no_mangle] pub extern "C" fn wglMakeCurrent() {}
#[no_mangle] pub extern "C" fn wglRealizeLayerPalette() {}
#[no_mangle] pub extern "C" fn wglSetLayerPaletteEntries() {}
#[no_mangle] pub extern "C" fn wglSetPixelFormat() {}
#[no_mangle] pub extern "C" fn wglShareLists() {}
#[no_mangle] pub extern "C" fn wglSwapBuffers() {}
#[no_mangle] pub extern "C" fn wglSwapLayerBuffers() {}
#[no_mangle] pub extern "C" fn wglUseFontBitmapsA() {}
#[no_mangle] pub extern "C" fn wglUseFontBitmapsW() {}
#[no_mangle] pub extern "C" fn wglUseFontOutlinesA() {}
#[no_mangle] pub extern "C" fn wglUseFontOutlinesW() {}